module.exports = {
  NO_INFORMATION_PROVIDED: "ALERTS.NO_INFORMATION_PROVIDED",
  MISSING_FIELDS: "ALERTS.MISSING_FIELDS",
  AUTH: {
    SUCCESS: {
      GITHUB_LINKED: "ALERTS.AUTH.SUCCESS.GITHUB_LINKED",
    },
    ERROR: {
      USER_NOT_FOUND: "ALERTS.AUTH.ERROR.USER_NOT_FOUND",
      USERNAME_INVALID: "ALERTS.AUTH.ERROR.USERNAME_INVALID",
      USERNAME_USED: "ALERTS.AUTH.ERROR.USERNAME_USED",
      EMAIL_INVALID: "ALERTS.AUTH.ERROR.EMAIL_INVALID",
      EMAIL_USED: "ALERTS.AUTH.ERROR.EMAIL_USED",
      PASSWORD_INVALID: "ALERTS.AUTH.ERROR.PASSWORD_INVALID",
      USERNAME_PASSWORD_INVALID: "ALERTS.AUTH.ERROR.USERNAME_PASSWORD_INVALID",
      TOKEN_NOT_PROVIDED: "ALERTS.AUTH.ERROR.TOKEN_NOT_PROVIDED",
      GITHUB_USED: "ALERTS.AUTH.ERROR.GITHUB_USED",
    },
  },
  EDUCATION: {
    SUCCESS: {
      UPDATED: "ALERTS.EDUCATION.SUCCESS.UPDATED",
      ITEM_UPDATED: "ALERTS.EDUCATION.SUCCESS.ITEM_UPDATED",
      ITEMS_UPDATED: "ALERTS.EDUCATION.SUCCESS.ITEMS_UPDATED",
      ITEM_REMOVED: "ALERTS.EDUCATION.SUCCESS.ITEM_REMOVED",
    },
    ERROR: {
      NOT_FOUND: "ALERTS.EDUCATION.ERROR.NOT_FOUND",
      ITEM_NOT_FOUND: "ALERTS.EDUCATION.ERROR.ITEM_NOT_FOUND",
    },
  },
};
