module.exports = {
  NO_INFORMATION_PROVIDED: "ALERTS.NO_INFORMATION_PROVIDED",
  MISSING_FIELDS: "ALERTS.MISSING_FIELDS",
  AUTH: {
    SUCCESS: {
      GITHUB_LINKED: "ALERTS.AUTH.SUCCESS.GITHUB_LINKED",
      EMAIL_VERIFICATION: "ALERTS.AUTH.SUCCESS.EMAIL_VERIFICATION",
    },
    ERROR: {
      USER_NOT_FOUND: "ALERTS.AUTH.ERROR.USER_NOT_FOUND",
      USERNAME_INVALID: "ALERTS.AUTH.ERROR.USERNAME_INVALID",
      USERNAME_USED: "ALERTS.AUTH.ERROR.USERNAME_USED",
      EMAIL_INVALID: "ALERTS.AUTH.ERROR.EMAIL_INVALID",
      EMAIL_USED: "ALERTS.AUTH.ERROR.EMAIL_USED",
      EMAIL_NOT_VERIFIED: "ALERTS.AUTH.ERROR.EMAIL_NOT_VERIFIED",
      PASSWORD_INVALID: "ALERTS.AUTH.ERROR.PASSWORD_INVALID",
      USERNAME_PASSWORD_INVALID: "ALERTS.AUTH.ERROR.USERNAME_PASSWORD_INVALID",
      TOKEN_NOT_PROVIDED: "ALERTS.AUTH.ERROR.TOKEN_NOT_PROVIDED",
      GITHUB_USED: "ALERTS.AUTH.ERROR.GITHUB_USED",
    },
  },
  EDUCATION: {
    SUCCESS: {
      UPDATED: "ALERTS.EDUCATION.SUCCESS.UPDATED",
      ITEMS_UPDATED: "ALERTS.EDUCATION.SUCCESS.ITEMS_UPDATED",
      ITEM_REMOVED: "ALERTS.EDUCATION.SUCCESS.ITEM_REMOVED",
    },
    ERROR: {
      NOT_FOUND: "ALERTS.EDUCATION.ERROR.NOT_FOUND",
      ITEM_NOT_FOUND: "ALERTS.EDUCATION.ERROR.ITEM_NOT_FOUND",
    },
  },
  EMPLOYMENT: {
    SUCCESS: {
      UPDATED: "ALERTS.EMPLOYMENT.SUCCESS.UPDATED",
      ITEMS_UPDATED: "ALERTS.EMPLOYMENT.SUCCESS.ITEMS_UPDATED",
      ITEM_REMOVED: "ALERTS.EMPLOYMENT.SUCCESS.ITEM_REMOVED",
    },
    ERROR: {
      NOT_FOUND: "ALERTS.EMPLOYMENT.ERROR.NOT_FOUND",
      ITEM_NOT_FOUND: "ALERTS.EMPLOYMENT.ERROR.ITEM_NOT_FOUND",
    },
  },
  PROFILE: {
    SUCCESS: {
      UPDATED: "ALERTS.PROFILE.SUCCESS.UPDATED",
      PROFILE_IMAGE_UPDATED: "ALERTS.PROFILE.SUCCESS.PROFILE_IMAGE_UPDATED",
      COVER_IMAGE_UPDATED: "ALERTS.PROFILE.SUCCESS.COVER_IMAGE_UPDATED",
    },
    ERROR: {
      FILE_NOT_PROVIDED: "ALERTS.PROFILE.ERROR.FILE_NOT_PROVIDED",
    },
  },
  PROJECTS: {
    SUCCESS: {
      UPDATED: "ALERTS.PROJECTS.SUCCESS.UPDATED",
      ITEMS_UPDATED: "ALERTS.PROJECTS.SUCCESS.ITEMS_UPDATED",
      ITEM_REMOVED: "ALERTS.PROJECTS.SUCCESS.ITEM_REMOVED",
    },
    ERROR: {
      NOT_FOUND: "ALERTS.PROJECTS.ERROR.NOT_FOUND",
      ITEM_NOT_FOUND: "ALERTS.PROJECTS.ERROR.ITEM_NOT_FOUND",
    },
  },
  SETTINGS: {
    SUCCESS: {
      UPDATED: "ALERTS.SETTINGS.SUCCESS.UPDATED",
      PASSWORD_UPDATED: "ALERTS.SETTINGS.SUCCESS.PASSWORD_UPDATED",
      DELETED: "ALERTS.SETTINGS.SUCCESS.DELETED",
    },
    ERROR: {
      NOT_FOUND: "ALERTS.SETTINGS.ERROR.NOT_FOUND",
      EDUCATION_DATA: "ALERTS.SETTINGS.ERROR.EDUCATION_DATA",
      EMPLOYMENT_DATA: "ALERTS.SETTINGS.ERROR.EMPLOYMENT_DATA",
      PROJECT_DATA: "ALERTS.SETTINGS.ERROR.PROJECT_DATA",
      CURRENT_PASSWORD_REQUIRED:
        "ALERTS.SETTINGS.ERROR.CURRENT_PASSWORD_REQUIRED",
      NEW_PASSWORD_REQUIRED: "ALERTS.SETTINGS.ERROR.NEW_PASSWORD_REQUIRED",
      PASSWORDS_MATCH: "ALERTS.SETTINGS.ERROR.PASSWORDS_MATCH",
      CURRENT_PASSWORD_INCORRECT:
        "ALERTS.SETTINGS.ERROR.CURRENT_PASSWORD_INCORRECT",
    },
  },
};
