// module.exports = [
//   { title: "AArch64", name: "aarch64" },
//   { title: "Adobe After Effects", name: "aftereffects" },
//   { title: "Adobe Illustrator", name: "illustrator" },
//   { title: "Adobe Photoshop", name: "photoshop" },
//   { title: "Adobe Premiere Pro", name: "premierepro" },
//   { title: "Adobe XD", name: "xd" },
//   { title: "AdonisJS", name: "adonisjs" },
//   { title: "Amazon Web Services", name: "amazonwebservices" },
//   { title: "Anaconda", name: "anaconda" },
//   { title: "Android", name: "android" },
//   { title: "Android Studio", name: "androidstudio" },
//   { title: "Angular", name: "angularjs" },
//   { title: "Ansible", name: "ansible" },
//   { title: "Apache", name: "apache" },
//   { title: "Apache Kafka", name: "apachekafka" },
//   { title: "Appcelerator", name: "appcelerator" },
//   { title: "Apple", name: "apple" },
//   { title: "Appwrite", name: "appwrite" },
//   { title: "Arduino", name: "arduino" },
//   { title: "Argo CD", name: "argocd" },
//   { title: "Atom", name: "atom" },
//   { title: "Azure", name: "azure" },
//   { title: "Babel", name: "babel" },
//   { title: "Backbone.js", name: "backbonejs" },
//   { title: "Bamboo", name: "bamboo" },
//   { title: "Bash", name: "bash" },
//   { title: "Behance", name: "behance" },
//   { title: "Bitbucket", name: "bitbucket" },
//   { title: "Blender", name: "blender" },
//   { title: "Bootstrap", name: "bootstrap" },
//   { title: "Bowe", name: "bower" },
//   { title: "Bulma", name: "bulma" },
//   { title: "C", name: "c" },
//   { title: "CakePHP", name: "cakephp" },
//   { title: "Canva", name: "canva" },
//   { title: "CentOS", name: "centos" },
//   { title: "Ceylon", name: "ceylon" },
//   { title: "Chrome", name: "chrome" },
//   { title: "CircleCI", name: "circleci" },
//   { title: "Clojure", name: "clojure" },
//   { title: "ClojureScript", name: "clojurescript" },
//   { title: "CMake", name: "cmake" },
//   { title: "Codecov", name: "codecov" },
//   { title: "CodeIgniter", name: "codeigniter" },
//   { title: "CodePen", name: "codepen" },
//   { title: "CoffeeScript", name: "coffeescript" },
//   { title: "Composer", name: "composer" },
//   { title: "Confluence", name: "confluence" },
//   { title: "CouchDB", name: "couchdb" },
//   { title: "C++", name: "cplusplus" },
//   { title: "Crystal", name: "crystal" },
//   { title: "C#", name: "csharp" },
//   { title: "CSS", name: "css3" },
//   { title: "Cucumber", name: "cucumber" },
//   { title: "D3.js", name: "d3js" },
//   { title: "Dart", name: "dart" },
//   { title: "Debian", name: "debian" },
//   { title: "Deno", name: "denojs" },
//   { title: "DigitalOcean", name: "digitalocean" },
//   { title: "discord.js", name: "discordjs" },
//   { title: "Django", name: "django" },
//   { title: "Docker", name: "docker" },
//   { title: "Doctrine", name: "doctrine" },
//   { title: ".NET", name: "dot-net" },
//   { title: ".NET Core", name: "dotnetcore" },
//   { title: "Dropwizard", name: "dropwizard" },
//   { title: "Drupal", name: "drupal" },
//   { title: "Electron", name: "electron" },
//   { title: "Eleventy", name: "eleventy" },
//   { title: "Elixir", name: "elixir" },
//   { title: "Elm", name: "elm" },
//   { title: "Embedded C", name: "embeddedc" },
//   { title: "Ember.js", name: "ember" },
//   { title: "Erlang", name: "erlang" },
//   { title: "ESLint", name: "eslint" },
//   { title: "Express.js", name: "express" },
//   { title: "Facebook", name: "facebook" },
//   { title: "FastAPI", name: "fastapi" },
//   { title: "Feathers", name: "feathersjs" },
//   { title: "Fedora", name: "fedora" },
//   { title: "Figma", name: "figma" },
//   { title: "FileZilla", name: "filezilla" },
//   { title: "Firebase", name: "firebase" },
//   { title: "Firefox", name: "firefox" },
//   { title: "Flask", name: "flask" },
//   { title: "Flutter", name: "flutter" },
//   { title: "Foundation", name: "foundation" },
//   { title: "F#", name: "fsharp" },
//   { title: "Gatling", name: "gatling" },
//   { title: "Gatsby", name: "gatsby" },
//   { title: "GCC", name: "gcc" },
//   { title: "Gentoo", name: "gentoo" },
//   { title: "GIMP", name: "gimp" },
//   { title: "Git", name: "git" },
//   { title: "GitHub", name: "github" },
//   { title: "GitLab", name: "gitlab" },
//   { title: "Gitter", name: "gitter" },
//   { title: "Go", name: "go" },
//   { title: "Godot", name: "godot" },
//   { title: "Google", name: "google" },
//   { title: "Google Cloud", name: "googlecloud" },
//   { title: "Gradle", name: "gradle" },
//   { title: "Grafana", name: "grafana" },
//   { title: "Grails", name: "grails" },
//   { title: "GraphQL", name: "graphql" },
//   { title: "Groovy", name: "groovy" },
//   { title: "Grunt", name: "grunt" },
//   { title: "Gulp.js", name: "gulp" },
//   { title: "Handlebars", name: "handlebars" },
//   { title: "Haskell", name: "haskell" },
//   { title: "Haxe", name: "haxe" },
//   { title: "Heroku", name: "heroku" },
//   { title: "HTML", name: "html5" },
//   { title: "Hugo", name: "hugo" },
//   { title: "IE10", name: "ie10" },
//   { title: "IFTTT", name: "ifttt" },
//   { title: "Inkscape ", name: "inkscape" },
//   { title: "IntelliJ", name: "intellij" },
//   { title: "Ionic", name: "ionic" },
//   { title: "Jamstack", name: "jamstack" },
//   { title: "Jasmine", name: "jasmine" },
//   { title: "Java", name: "java" },
//   { title: "JavaScript", name: "javascript" },
//   { title: "Jeet", name: "jeet" },
//   { title: "Jenkins", name: "jenkins" },
//   { title: "Jest", name: "jest" },
//   { title: "JetBrains", name: "jetbrains" },
//   { title: "Jira", name: "jira" },
//   { title: "jQuery", name: "jquery" },
//   { title: "Julia", name: "julia" },
//   { title: "Jupyter ", name: "jupyter" },
//   { title: "K3s", name: "k3s" },
//   { title: "Kaggle", name: "kaggle" },
//   { title: "Karma", name: "karma" },
//   { title: "Knockout", name: "knockout" },
//   { title: "Kotlin", name: "kotlin" },
//   { title: "Kraken.js", name: "krakenjs" },
//   { title: "Kubernetes", name: "kubernetes" },
//   { title: "LabVIEW", name: "labview" },
//   { title: "Laravel", name: "laravel" },
//   { title: "LaTeX", name: "latex" },
//   { title: "Less", name: "less" },
//   { title: "Linux", name: "linux" },
//   { title: "Lua", name: "lua" },
//   { title: "Magento", name: "magento" },
//   { title: "Markdown ", name: "markdown" },
//   { title: "Material UI", name: "materialui" },
//   { title: "MATLAB", name: "matlab" },
//   { title: "Maya", name: "maya" },
//   { title: "Meteor", name: "meteor" },
//   { title: "Microsoft SQL Server", name: "microsoftsqlserver" },
//   { title: "Minitab", name: "minitab" },
//   { title: "Mocha", name: "mocha" },
//   { title: "MODX", name: "modx" },
//   { title: "MongoDB ", name: "mongodb" },
//   { title: "Moodle", name: "moodle" },
//   { title: "MS-DOS", name: "msdos" },
//   { title: "MySQL ", name: "mysql" },
//   { title: "Neo4j", name: "neo4j" },
//   { title: "NestJS", name: "nestjs" },
//   { title: "NetworkX", name: "networkx" },
//   { title: "Next.js", name: "nextjs" },
//   { title: "NGINX", name: "nginx" },
//   { title: "Nix", name: "nixos" },
//   { title: "Node.js", name: "nodejs" },
//   { title: "NW.js", name: "nodewebkit" },
//   { title: "npm", name: "npm" },
//   { title: "NuGet", name: "nuget" },
//   { title: "NumPy ", name: "numpy" },
//   { title: "Nuxt.js", name: "nuxtjs" },
//   { title: "Objective-C", name: "objectivec" },
//   { title: "OCaml", name: "ocaml" },
//   { title: "OpenAL", name: "openal" },
//   { title: "OpenCV", name: "opencv" },
//   { title: "OpenGL", name: "opengl" },
//   { title: "openSUSE", name: "opensuse" },
//   { title: "Opera", name: "opera" },
//   { title: "Oracle", name: "oracle" },
//   { title: "Packer", name: "packer" },
//   { title: "Pandas", name: "pandas" },
//   { title: "Perl", name: "perl" },
//   { title: "Phalcon", name: "phalcon" },
//   { title: "Phoenix", name: "phoenix" },
//   { title: "PHP", name: "php" },
//   { title: "PhpStorm", name: "phpstorm" },
//   { title: "Podman", name: "podman" },
//   { title: "Polygon", name: "polygon" },
//   { title: "PostgreSQL", name: "postgresql" },
//   { title: "Processing", name: "processing" },
//   { title: "Prometheus", name: "prometheus" },
//   { title: "Protractor", name: "protractor" },
//   { title: "PuTTY", name: "putty" },
//   { title: "PyCharm", name: "pycharm" },
//   { title: "PyTest", name: "pytest" },
//   { title: "Python", name: "python" },
//   { title: "PyTorch ", name: "pytorch" },
//   { title: "Qt", name: "qt" },
//   { title: "R", name: "r" },
//   { title: "Rails", name: "rails" },
//   { title: "Raspberry Pi", name: "raspberrypi" },
//   { title: "React", name: "react" },
//   { title: "Rect", name: "rect" },
//   { title: "Red Hat", name: "redhat" },
//   { title: "Redis", name: "redis" },
//   { title: "Redux", name: "redux" },
//   { title: "RocksDB", name: "rocksdb" },
//   { title: "RSpec", name: "rspec" },
//   { title: "RStudio", name: "rstudio" },
//   { title: "Ruby", name: "ruby" },
//   { title: "RubyMine", name: "rubymine" },
//   { title: "Rust", name: "rust" },
//   { title: "Safari", name: "safari" },
//   { title: "Salesforce", name: "salesforce" },
//   { title: "Sass", name: "sass" },
//   { title: "Scala ", name: "scala" },
//   { title: "SDL", name: "sdl" },
//   { title: "Selenium", name: "selenium" },
//   { title: "Sequelize", name: "sequelize" },
//   { title: "Shopware", name: "shopware" },
//   { title: "ShotGrid", name: "shotgrid" },
//   { title: "Scratch", name: "sketch" },
//   { title: "Slack", name: "slack" },
//   { title: "Socket.IO", name: "socketio" },
//   { title: "Solidity", name: "solidity" },
//   { title: "Sourcetree", name: "sourcetree" },
//   { title: "Spring", name: "spring" },
//   { title: "SPSS ", name: "spss" },
//   { title: "SQLAlchemy", name: "sqlalchemy" },
//   { title: "SQLite", name: "sqlite" },
//   { title: "SSH", name: "ssh" },
//   { title: "Storybook", name: "storybook" },
//   { title: "Stylus", name: "stylus" },
//   { title: "Subversion", name: "subversion" },
//   { title: "Svelte", name: "svelte" },
//   { title: "Swift", name: "swift" },
//   { title: "Symfony", name: "symfony" },
//   { title: "Tailwind CSS", name: "tailwindcss" },
//   { title: "TensorFlow", name: "tensorflow" },
//   { title: "Terraform", name: "terraform" },
//   { title: "The Algorithms", name: "thealgorithms" },
//   { title: "Three.js", name: "threejs" },
//   { title: "Tomcat", name: "tomcat" },
//   { title: "TortoiseGit", name: "tortoisegit" },
//   { title: "Tower Git", name: "towergit" },
//   { title: "Travis CI", name: "travis" },
//   { title: "X", name: "x" },
//   { title: "TypeScript", name: "typescript" },
//   { title: "TYPO3", name: "typo3" },
//   { title: "Ubuntu", name: "ubuntu" },
//   { title: "Unity", name: "unity" },
//   { title: "Unix", name: "unix" },
//   { title: "Unreal Engine", name: "unrealengine" },
//   { title: "uWSGI", name: "uwsgi" },
//   { title: "Vagrant", name: "vagrant" },
//   { title: "Vim", name: "vim" },
//   { title: "Visual Studio", name: "visualstudio" },
//   { title: "VS Code", name: "vscode" },
//   { title: "Vue.js", name: "vuejs" },
//   { title: "Vue Storefront", name: "vuestorefront" },
//   { title: "Vuetify", name: "vuetify" },
//   { title: "Webflow", name: "webflow" },
//   { title: "Weblate", name: "weblate" },
//   { title: "Webpack", name: "webpack" },
//   { title: "WebStorm", name: "webstorm" },
//   { title: "Windows 8", name: "windows8" },
//   { title: "WooCommerce", name: "woocommerce" },
//   { title: "WordPress", name: "wordpress" },
//   { title: "Xamarin", name: "xamarin" },
//   { title: "Xcode", name: "xcode" },
//   { title: "Yarn", name: "yarn" },
//   { title: "Yii", name: "yii" },
//   { title: "YunoHost", name: "yunohost" },
//   { title: "Zend", name: "zend" },
//   { title: "Zig", name: "zig" },
// ];
